### PR TITLE
Modified splash screen to show 'Continue Tour' if a tour had already …

### PR DESCRIPTION
**Pull request by BobTorgerson**
…been started but not ended. This resolves the GH Issue #235

---
This change is [Reviewable](https://reviewable.io/reviews/ua-snap/mapventure/257)

### CODE REVIEW

**Comment by BobTorgerson** [comment]
Github Issue #261 has been resolved with the most recent commit.

**Comment by BobTorgerson** [comment]
The latest commit resolves Github issue #262

**Comment by brucecrevensten** [comment]
Reviewed 1 of 3 files at r3, 1 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/scripts/controllers/map.js, line 380 at r5](https://reviewable.io:443/reviews/ua-snap/mapventure/257#-Kh3EnOFh_UEdbWY3Gf7:-Kh3EnOFh_UEdbWY3Gf8:bofle9x) ([raw file](https://github.com/ua-snap/mapventure/blob/ac33859abf1e2950d50a8953da09db172c0f7eee/app/scripts/controllers/map.js#L380)):*
> ```JavaScript
> 
>     $scope.startTour = function(tourStep) {
>       if (tourStep == null || tourStep == 0) {
> ```

OK, first, this seems to (mostly) work -- yay! -- and not to be too pedantic here, but is the purpose of this step to identify: (A) "Tour is not started, or is on the first (0th) step" or (B) "Tour is not started"?  Point being that tours do start on array index 0 (= "first" step).

If (A), I'd suggest stepping up to a strict equality operator on the right (`tourStep === 0`).
If (B), drop the 2nd clause entirely.

As it is, the first tour step shows up under the splash screen.  (translucency makes it hard to spot but you can see it):



---

*[app/views/mapSplashScreen.html, line 6 at r5](https://reviewable.io:443/reviews/ua-snap/mapventure/257#-Kh3IhcWggjnd9X-y65-:-Kh3IhcWggjnd9X-y650:b-j7epwx) ([raw file](https://github.com/ua-snap/mapventure/blob/ac33859abf1e2950d50a8953da09db172c0f7eee/app/views/mapSplashScreen.html#L6)):*
> ```HTML
>     <div class="buttons">
>       <button type="button" class="btn btn-lg btn-success" ng-click="hideSplash=true; startTour(tour._current)" ng-disabled="showMapButtonDisabled" disabled="disabled">
>         <span ng-show="tour._current == null || tour._current == 0">Take a tour of this map&hellip;</span>
> ```

Same as above, decide if the `== 0` is appropriate here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ua-snap/mapventure/257)*

**Comment by BobTorgerson** [comment]
Reviewed 1 of 3 files at r3, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ua-snap/mapventure/257)*

**Pull request merged**
