### PR TITLE
Add graph to tour

### PR DESCRIPTION
**Pull request by cstephen**
This change is [Reviewable](https://reviewable.io/reviews/ua-snap/mapventure/322)

### CODE REVIEW

**Comment by cstephen** [comment]
This fixes #308.

**Comment by brucecrevensten** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/scripts/maps/alaska-wildfires/tour.js, line 138 at r1](https://reviewable.io:443/reviews/ua-snap/mapventure/322#-KkIfIQ0KkwbABYWx0t9:-KkIfIQ0KkwbABYWx0tA:by9gbyv) ([raw file](https://github.com/ua-snap/mapventure/blob/41a4e868fa572e214d8886431ffcde877dfdb621/app/scripts/maps/alaska-wildfires/tour.js#L138)):*
> ```JavaScript
>                 .removeClass('zoom');
>             }
>           },
> ```

Remove this step

---

*[app/scripts/maps/alaska-wildfires/tour.js, line 142 at r1](https://reviewable.io:443/reviews/ua-snap/mapventure/322#-KkIfKECSJJSNDcU4NUg:-KkIfKECSJJSNDcU4NUh:bfjvqmx) ([raw file](https://github.com/ua-snap/mapventure/blob/41a4e868fa572e214d8886431ffcde877dfdb621/app/scripts/maps/alaska-wildfires/tour.js#L142)):*
> ```JavaScript
>             title: 'Large fire seasons',
>             element: '.js-plotly-plot .legend',
>             content: 'This chart includes the largest fire seasons on record since 2004 and the current year for comparison.',
> ```

Update text to match doc

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ua-snap/mapventure/322)*

**Comment by brucecrevensten** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ua-snap/mapventure/322)*

**Comment by brucecrevensten** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ua-snap/mapventure/322)*

**Pull request merged**
