### PR TITLE
Plotly graph

### PR DESCRIPTION
**Pull request by cstephen**
This change is [Reviewable](https://reviewable.io/reviews/ua-snap/mapventure/299)

### CODE REVIEW

**Comment by brucecrevensten** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[bower.json, line 26 at r1](https://reviewable.io:443/reviews/ua-snap/mapventure/299#-Kji9xqxRr4RSWuMtj65:-Kji9xqxRr4RSWuMtj66:b-apsgrk) ([raw file](https://github.com/ua-snap/mapventure/blob/51604257df97b88bac90796cf4e549059e97cc1d/bower.json#L26)):*
> ```JSON
>     "angular-moment": "^0.10.3",
>     "angular-markdown-filter": "^1.4.0",
>     "angular-plotly": "^0.1.3"
> ```

suggest changing this to a `~0.1.3` for `angular-plotly`.  (Same for `angular-markdown-filter` just because `git` sees it a also an added line! :smile:)

---

*[app/scripts/maps/alaska-wildfires/controller.js, line 298 at r1](https://reviewable.io:443/reviews/ua-snap/mapventure/299#-KjiMyXox8ai7smhnQgv:-KjiMyXox8ai7smhnQgw:b-ys2sjs) ([raw file](https://github.com/ua-snap/mapventure/blob/51604257df97b88bac90796cf4e549059e97cc1d/app/scripts/maps/alaska-wildfires/controller.js#L298)):*
> ```JavaScript
> 
>     $scope.graphLayout.titlefont = {
>       size: 20
> ```

Can you add the [relevant code](https://plot.ly/javascript/font/) in here -- and throughout -- to make the font Lato to be consistent with the rest of the app?

---

*[app/scripts/maps/alaska-wildfires/controller.js, line 350 at r1](https://reviewable.io:443/reviews/ua-snap/mapventure/299#-KjiIHMrvssKXlO8lHzN:-KjiIHMrvssKXlO8lHzO:b-kc3jgk) ([raw file](https://github.com/ua-snap/mapventure/blob/51604257df97b88bac90796cf4e549059e97cc1d/app/scripts/maps/alaska-wildfires/controller.js#L350)):*
> ```JavaScript
> 
>       years.forEach(function(year) {
>         Fire.getTimeSeries(year).then(function success(res) {
> ```

This seems to be loading the data twice -- first it happens in `getHighestFireYears`, then again here.  Could this be modified to use the data that has already been loaded?

---

*[app/scripts/services/fire.js, line 33 at r1](https://reviewable.io:443/reviews/ua-snap/mapventure/299#-KjiHw1iRMCfRAiGRxs9:-KjiHw1iRMCfRAiGRxsA:b-r5ax3n) ([raw file](https://github.com/ua-snap/mapventure/blob/51604257df97b88bac90796cf4e549059e97cc1d/app/scripts/services/fire.js#L33)):*
> ```JavaScript
>           // in the next step.
>           var yearsWithArea = years.map(function(year) {
>             return $http.get('/' + year + '.json').then(function(res) {
> ```

Instead of fetching raw data from the past, could this instead simply grab a single data file that contains the known highest 5 fire years?

---

*[app/scripts/services/fire.js, line 53 at r1](https://reviewable.io:443/reviews/ua-snap/mapventure/299#-KjiKZgqWVdoLHhECEwA:-KjiKZgqWVdoLHhECEwB:b-q4vujy) ([raw file](https://github.com/ua-snap/mapventure/blob/51604257df97b88bac90796cf4e549059e97cc1d/app/scripts/services/fire.js#L53)):*
> ```JavaScript
> 
>             // Return a subset of sorted years.
>             return sortedYears.slice(0, numberOfYears);
> ```

Along the lines of the above comments asking about reducing the number of HTTP requests (combine historical data into a single lump), can it also be pre-sorted, etc?  I know it's not much effort on the client but we'd still get a bit of a performance boost and it shouldn't be hard to do.

---

*[app/styles/map.scss, line 191 at r1](https://reviewable.io:443/reviews/ua-snap/mapventure/299#-KjiLWx8zd5yzxbg7-EX:-KjiLWx8zd5yzxbg7-EY:b-y10cpl) ([raw file](https://github.com/ua-snap/mapventure/blob/51604257df97b88bac90796cf4e549059e97cc1d/app/styles/map.scss#L191)):*
> ```SCSS
> }
> 
> .graph-screen {
> ```

Can this be moved into the `app/maps/alaska-wildfires/alaska-wildfires.scss` file?  I  know that the directive shows up at the global scope (no easy way around that as far as I know, with our current structure), but it's really only going to be invoked via the fire map.

---

*[app/styles/map.scss, line 203 at r1](https://reviewable.io:443/reviews/ua-snap/mapventure/299#-KjiLzD8Vs_fjak0lULF:-KjiLzD8Vs_fjak0lULG:b-5y4gl8) ([raw file](https://github.com/ua-snap/mapventure/blob/51604257df97b88bac90796cf4e549059e97cc1d/app/styles/map.scss#L203)):*
> ```SCSS
>     width: 80%;
>     margin: 4rem auto;
> ```

I suggest adding `box-shadow: 0px 10px 40px 0px rgba(0,0,0,0.75);` here too.  It looks nice!  :smiley: 

---

*[app/views/map.html, line 69 at r1](https://reviewable.io:443/reviews/ua-snap/mapventure/299#-KjiE2n8-OpWiyidxsfR:-KjiE2n8-OpWiyidxsfS:blcin5n) ([raw file](https://github.com/ua-snap/mapventure/blob/51604257df97b88bac90796cf4e549059e97cc1d/app/views/map.html#L69)):*
> ```HTML
>       <span class="glyphicon glyphicon-signal"></span>
>       &nbsp;
>       Graph {{ graphLayout.title }}&hellip;
> ```

Perhaps change thins to be: `Graph large fire seasons&hellip;` so it matches the caps style of other buttons.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ua-snap/mapventure/299)*

**Comment by brucecrevensten** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/ua-snap/mapventure/299#-KjiOzyUYkaA2Xm8v10v:-KjiOzyUYkaA2Xm8v10w:bl7eqo8) (no related file):*
Also, I think the static historical fire data can be hosted within this repository, perhaps at `app/scripts/maps/alaska-wildfires/(data)` however this would need to be tested after a `grunt build` to ensure that it works right in a "real hosted" situation.  I'm a little unclear on that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ua-snap/mapventure/299)*

**Comment by brucecrevensten** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[app/scripts/services/fire.js, line 22 at r1](https://reviewable.io:443/reviews/ua-snap/mapventure/299#-KjiQ7JJw95lVyfZDifh:-KjiQ7JJw95lVyfZDifi:b-g0ms2f) ([raw file](https://github.com/ua-snap/mapventure/blob/51604257df97b88bac90796cf4e549059e97cc1d/app/scripts/services/fire.js#L22)):*
> ```JavaScript
>     this.$get = function($http) {
>       return {
>         getFeatures: function() {
> ```

I think a brief comment would be nice above this function: "This fetches current fire positions from a GeoJSON endpoint."  Just to help distinguish what this is doing from what the graph/time series is doing.  Some comments on the other service functions would be nice, too, nothing big or special needed -- just purpose/why.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ua-snap/mapventure/299)*

**Comment by cstephen** [comment]
*[bower.json, line 26 at r1](https://reviewable.io:443/reviews/ua-snap/mapventure/299#-Kji9xqxRr4RSWuMtj65:-KjiVx6w28GawydZAtZE:b9fgmb9) ([raw file](https://github.com/ua-snap/mapventure/blob/51604257df97b88bac90796cf4e549059e97cc1d/bower.json#L26)):*
<details><summary><i>Previously, brucecrevensten (Bruce Crevensten) wrote…</i></summary><blockquote>

suggest changing this to a `~0.1.3` for `angular-plotly`.  (Same for `angular-markdown-filter` just because `git` sees it a also an added line! :smile:)
</blockquote></details>

I'll go ahead and change `angular-plotly` to `~0.1.3`. I agree that we should change `angular-markdown-filter` (and probably all of the other Bower packages) to use `~`, but I think the others are best handled in a different PR to keep things compartmentalized and easier to track in the future.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ua-snap/mapventure/299)*

**Comment by cstephen** [comment]
*[app/scripts/maps/alaska-wildfires/controller.js, line 298 at r1](https://reviewable.io:443/reviews/ua-snap/mapventure/299#-KjiMyXox8ai7smhnQgv:-KjioVSjWs44zWdhMMYX:bmk1e57) ([raw file](https://github.com/ua-snap/mapventure/blob/51604257df97b88bac90796cf4e549059e97cc1d/app/scripts/maps/alaska-wildfires/controller.js#L298)):*
<details><summary><i>Previously, brucecrevensten (Bruce Crevensten) wrote…</i></summary><blockquote>

Can you add the [relevant code](https://plot.ly/javascript/font/) in here -- and throughout -- to make the font Lato to be consistent with the rest of the app?
</blockquote></details>

I changed Plotly's global font to Lato. This changed everything except for the hover text that appears when you mouse over data points. I couldn't find any documentation on how to change that, but we might not even want that. What do think, @brucecrevensten?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ua-snap/mapventure/299)*

**Comment by brucecrevensten** [comment]
Review status: 5 of 10 files reviewed at latest revision, 9 unresolved discussions.

---

*[app/scripts/maps/alaska-wildfires/controller.js, line 298 at r1](https://reviewable.io:443/reviews/ua-snap/mapventure/299#-KjiMyXox8ai7smhnQgv:-Kjj0ms4QxLezImtJqQa:buw3jlr) ([raw file](https://github.com/ua-snap/mapventure/blob/51604257df97b88bac90796cf4e549059e97cc1d/app/scripts/maps/alaska-wildfires/controller.js#L298)):*
<details><summary><i>Previously, cstephen (Craig Stephenson) wrote…</i></summary><blockquote>

I changed Plotly's global font to Lato. This changed everything except for the hover text that appears when you mouse over data points. I couldn't find any documentation on how to change that, but we might not even want that. What do think, @brucecrevensten?
</blockquote></details>

Yeah, that's fine to leave alone until/unless we get more feedback.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ua-snap/mapventure/299)*

**Comment by brucecrevensten** [comment]
Reviewed 6 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ua-snap/mapventure/299)*

**Comment by cstephen** [comment]
Review status: 8 of 10 files reviewed at latest revision, 8 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/ua-snap/mapventure/299#-KjiOzyUYkaA2Xm8v10v:-KjoSjzg22pSpdm7dGgm:b-j4r224) (no related file):*
<details><summary><i>Previously, brucecrevensten (Bruce Crevensten) wrote…</i></summary><blockquote>

Also, I think the static historical fire data can be hosted within this repository, perhaps at `app/scripts/maps/alaska-wildfires/(data)` however this would need to be tested after a `grunt build` to ensure that it works right in a "real hosted" situation.  I'm a little unclear on that.
</blockquote></details>

This suggestion is no longer relevant due to our new fire time series API endpoint. But I did remove our earlier attempts to incorporate the JSON data files into this repo.

---

*[bower.json, line 26 at r1](https://reviewable.io:443/reviews/ua-snap/mapventure/299#-Kji9xqxRr4RSWuMtj65:-KjiXqOxpA0N_9JdQd_F:b-896fix) ([raw file](https://github.com/ua-snap/mapventure/blob/51604257df97b88bac90796cf4e549059e97cc1d/bower.json#L26)):*
<details><summary><i>Previously, cstephen (Craig Stephenson) wrote…</i></summary><blockquote>

I'll go ahead and change `angular-plotly` to `~0.1.3`. I agree that we should change `angular-markdown-filter` (and probably all of the other Bower packages) to use `~`, but I think the others are best handled in a different PR to keep things compartmentalized and easier to track in the future.
</blockquote></details>

Done.

---

*[app/scripts/services/fire.js, line 22 at r1](https://reviewable.io:443/reviews/ua-snap/mapventure/299#-KjiQ7JJw95lVyfZDifh:-KjoSfx1nErJD-zyotNX:b-896fix) ([raw file](https://github.com/ua-snap/mapventure/blob/51604257df97b88bac90796cf4e549059e97cc1d/app/scripts/services/fire.js#L22)):*
<details><summary><i>Previously, brucecrevensten (Bruce Crevensten) wrote…</i></summary><blockquote>

I think a brief comment would be nice above this function: "This fetches current fire positions from a GeoJSON endpoint."  Just to help distinguish what this is doing from what the graph/time series is doing.  Some comments on the other service functions would be nice, too, nothing big or special needed -- just purpose/why.
</blockquote></details>

Done.

---

*[app/scripts/services/fire.js, line 33 at r1](https://reviewable.io:443/reviews/ua-snap/mapventure/299#-KjiHw1iRMCfRAiGRxs9:-KjoSPOOKtv5wpTKzbJu:b-jn698m) ([raw file](https://github.com/ua-snap/mapventure/blob/51604257df97b88bac90796cf4e549059e97cc1d/app/scripts/services/fire.js#L33)):*
<details><summary><i>Previously, brucecrevensten (Bruce Crevensten) wrote…</i></summary><blockquote>

Instead of fetching raw data from the past, could this instead simply grab a single data file that contains the known highest 5 fire years?
</blockquote></details>

This suggestion has been incorporated into our new fire time series API endpoint.

---

*[app/scripts/services/fire.js, line 53 at r1](https://reviewable.io:443/reviews/ua-snap/mapventure/299#-KjiKZgqWVdoLHhECEwA:-KjoSej5QMsNhIX64snY:b-jn698m) ([raw file](https://github.com/ua-snap/mapventure/blob/51604257df97b88bac90796cf4e549059e97cc1d/app/scripts/services/fire.js#L53)):*
<details><summary><i>Previously, brucecrevensten (Bruce Crevensten) wrote…</i></summary><blockquote>

Along the lines of the above comments asking about reducing the number of HTTP requests (combine historical data into a single lump), can it also be pre-sorted, etc?  I know it's not much effort on the client but we'd still get a bit of a performance boost and it shouldn't be hard to do.
</blockquote></details>

This suggestion has been incorporated into our new fire time series API endpoint.

---

*[app/views/map.html, line 69 at r1](https://reviewable.io:443/reviews/ua-snap/mapventure/299#-KjiE2n8-OpWiyidxsfR:-KjoT7QgaV6I852x2uEg:b-896fix) ([raw file](https://github.com/ua-snap/mapventure/blob/51604257df97b88bac90796cf4e549059e97cc1d/app/views/map.html#L69)):*
<details><summary><i>Previously, brucecrevensten (Bruce Crevensten) wrote…</i></summary><blockquote>

Perhaps change thins to be: `Graph large fire seasons&hellip;` so it matches the caps style of other buttons.
</blockquote></details>

Done.

---

*[app/styles/map.scss, line 191 at r1](https://reviewable.io:443/reviews/ua-snap/mapventure/299#-KjiLWx8zd5yzxbg7-EX:-KjoT8C0gkXLHZA8VkML:b-896fix) ([raw file](https://github.com/ua-snap/mapventure/blob/51604257df97b88bac90796cf4e549059e97cc1d/app/styles/map.scss#L191)):*
<details><summary><i>Previously, brucecrevensten (Bruce Crevensten) wrote…</i></summary><blockquote>

Can this be moved into the `app/maps/alaska-wildfires/alaska-wildfires.scss` file?  I  know that the directive shows up at the global scope (no easy way around that as far as I know, with our current structure), but it's really only going to be invoked via the fire map.
</blockquote></details>

Done.

---

*[app/styles/map.scss, line 203 at r1](https://reviewable.io:443/reviews/ua-snap/mapventure/299#-KjiLzD8Vs_fjak0lULF:-KjoTB4mN7jxgecrkMv9:b-896fix) ([raw file](https://github.com/ua-snap/mapventure/blob/51604257df97b88bac90796cf4e549059e97cc1d/app/styles/map.scss#L203)):*
<details><summary><i>Previously, brucecrevensten (Bruce Crevensten) wrote…</i></summary><blockquote>

I suggest adding `box-shadow: 0px 10px 40px 0px rgba(0,0,0,0.75);` here too.  It looks nice!  :smiley: 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ua-snap/mapventure/299)*

**Comment by cstephen** [comment]
Review status: 8 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/scripts/maps/alaska-wildfires/controller.js, line 350 at r1](https://reviewable.io:443/reviews/ua-snap/mapventure/299#-KjiIHMrvssKXlO8lHzN:-KjoTF2D2oi0Z_ztBdm3:bo5ja79) ([raw file](https://github.com/ua-snap/mapventure/blob/51604257df97b88bac90796cf4e549059e97cc1d/app/scripts/maps/alaska-wildfires/controller.js#L350)):*
<details><summary><i>Previously, brucecrevensten (Bruce Crevensten) wrote…</i></summary><blockquote>

This seems to be loading the data twice -- first it happens in `getHighestFireYears`, then again here.  Could this be modified to use the data that has already been loaded?
</blockquote></details>

This has been resolved by grabbing everything all at once, pre-sorted, from the new fire time series API endpoint.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ua-snap/mapventure/299)*

**Comment by cstephen** [comment]
Review status: 8 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/scripts/maps/alaska-wildfires/controller.js, line 350 at r1](https://reviewable.io:443/reviews/ua-snap/mapventure/299#-KjiIHMrvssKXlO8lHzN:-KjoTMYq_1cCFnlvzH7g:b-896fix) ([raw file](https://github.com/ua-snap/mapventure/blob/51604257df97b88bac90796cf4e549059e97cc1d/app/scripts/maps/alaska-wildfires/controller.js#L350)):*
<details><summary><i>Previously, cstephen (Craig Stephenson) wrote…</i></summary><blockquote>

This has been resolved by grabbing everything all at once, pre-sorted, from the new fire time series API endpoint.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ua-snap/mapventure/299)*

**Comment by cstephen** [comment]
Review status: 8 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/ua-snap/mapventure/299#-KjiOzyUYkaA2Xm8v10v:-KjoTW-6nc8F0bdU3bwZ:b-896fix) (no related file):*
<details><summary><i>Previously, cstephen (Craig Stephenson) wrote…</i></summary><blockquote>

This suggestion is no longer relevant due to our new fire time series API endpoint. But I did remove our earlier attempts to incorporate the JSON data files into this repo.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ua-snap/mapventure/299)*

**Comment by brucecrevensten** [comment]
Reviewed 1 of 7 files at r2, 2 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ua-snap/mapventure/299)*

**Pull request merged**
