### PR TITLE
Refs #269, #215, fix ability to hide/show fire map markers

### PR DESCRIPTION
**Pull request by brucecrevensten**
This pull request adds the ability for a "local layer" to be handled by the custom map controller.

In this case, the local layer is fetched from a JSON endpoint and processed into markers and polygons on the map.

---
This change is [Reviewable](https://reviewable.io/reviews/ua-snap/mapventure/285)

### CODE REVIEW

**Comment by brucecrevensten** [comment]
Some TODOs before this can be merged:

- [ ] Make info sidebar work for the local custom layer
- [ ] Attach event popups for all desired things (fires over 1 acre??  need some discussion here)
- [ ] What to do about the JSON endpoint URL being hardcoded there?
- [ ] Handle error conditions if upstream network is failing
- [ ] Code review

**Comment by cstephen** [comment]
The "All fires, 2017" visibility toggle button doesn't work quite right. It hides the layer when I click it, but the button itself does not toggle "off" and then no longer does anything after that.

**Comment by cstephen** [comment]
The "All fires, 2017" visibility toggle button issue has been fixed with f0046f1.

**Comment by BobTorgerson** [comment]
Everything looks good to me in this PR! I have it working on my local machine and all of the changes make sense. 

---

Reviewed 2 of 3 files at r3, 2 of 8 files at r4, 4 of 5 files at r6, 3 of 5 files at r7, 2 of 2 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ua-snap/mapventure/285#-:-KjLAYg6OGPhvGPzfDkG:btidrml)*

**Pull request merged**
